a = input("Digite:")
print("O tipo primitivo desse valor é", type(a))
print("So tem espaços?", a.isspace())
print("é um numero? ", a.isnumeric())
print("é alfabético?", a.isalpha)
print("È alfanumerico?", a.isalnum())
print("ele é maiuscula?", a.isupper())
print("esta minuscula?", a.lower())
print("é capitaçizado", a.istitle())